---
version: 3

additional_build_files:
    - src: ansible.cfg
      dest: configs
images:
  base_image:
    name: <aap_hub_url>/ee-supported-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
